### ISSUE TITLE
gitmodules file needs to be updated for the dependencies #188

### ISSUE THREAD

**Issue by n-92** [esp-cpp/esp-box-emu#69]
### Answers checklist.

- [X] I have read the documentation and the issue is not addressed there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hello,

Github does not allow cloning anymore over non https. Could it be possible to make changes in gitmodules file so that the submodule cloning works?

**Comment by finger563** [comment]
It appears it's the espp repo which has a non-ssh submodule so both need to be updated.

**Comment by finger563** [comment]
Can you provide the issue you're seeing? Clones over https still seem to work for me.
